#name: Run Tests
#
#on: [push]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.9'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install --no-cache-dir spacy==3.7.5 scispacy==0.5.4 scipy==1.10.1 scikit-learn==1.1.2 uvicorn fastapi httpx pytest
#        pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_ner_bc5cdr_md-0.5.4.tar.gz
#
#    - name: Run tests
#      run: |
#        python -m unittest tests/test_ner.py
